### PR TITLE
[TEST PR - NO MERGE] tweak CIs to test locking fix

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
oh, wait, I need to issue this against the main feedstock, not your branch....

I forked your branch, I guess that's why I got mixed up.

**Comment by jakirkham** [comment]
Oh, that's tricky. Yeah, it should be fine as long as you don't change the version number or build number.

**Comment by jakirkham** [comment]
...or I can enable CI here.

**Comment by jakirkham** [comment]
Would the latter work for you?

**Comment by msarahan** [comment]
Already opened another one on the feedstock.  Closing here.

**Comment by jakirkham** [comment]
Ok.

**Pull request closed without merging**
